version = 0.1

[default.deploy.parameters]
stack_name = "spring-boot-cloud-function-aws-lambda"
resolve_s3 = true
s3_prefix = "spring-boot-cloud-function-aws-lambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
